---
# a simple top-level element
foo: 10



num_rounds: 10
num_clients: 100
batch_size: 20
num_classes: 10
num_clients_per_round_fit: 10
num_clients_per_round_eval: 25
config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 1

# method:
#   name: "fpzip"
#   precision: 0.1
method:
  name: "zfp"
  tolerance: 1e-3
  precision: 0.1
  rate: 0.1


defaults:
  - model: resnet18 # points to conf/models/resnet18.yaml
  - strategy: fedavg # points to conf/strategy/fedavg.yaml